spring:
  application:
    name: authentication-service-default
  datasource:
    url: jdbc:postgresql://localhost:5432/sm-user-account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  messages:
    basename: lang/messages

authentication:
  security:
    enable-https: false
    basic-user: api
    basic-password: api
    origin-allowed: http://localhost:4200
