spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sm-company
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  messages:
    basename: lang/messages

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
server:
  port: 8082
