server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  messages:
    basename: lang/messages

#Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
