spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: company-service
          uri: http://localhost:8082
          predicates:
            - Path=/company/**
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/customer/**
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
