server:
  port: 8084

spring:
  profiles:
    active: dev
  application:
    name: notificataion-service
  messages:
    basename: lang/messages
  freemarker:
    template-loader-path: classpath:/templates/
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    producer:
      retries: 3

#Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
